### PR TITLE
Remove explicit content-length header for GET requests

### LINKED ISSUE #701: S3Client is failed mkdir() with StreamHandler.
S3Client's streamwrapper is not working with StreamHandler.

For example:
```php
use Aws\S3\S3Client;
use Aws\Handler\GuzzleV6\GuzzleHandler;
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\StreamHandler;

$stack = HandlerStack::create(new StreamHandler());
$handler = GuzzleHandler(new Client(['handler' => $stack]));
$client = new S3Client(['http_handler' => $handler]);
$client->registerStreamWrapper();

mkdir('s3://mybucket/newdir'); # error!
```

error message:
```
PHP Warning:  Error executing "PutObject" on "https://s3-ap-northeast-1.amazonaw
s.com/mybucket/newdir/"; AWS HTTP error: Client error:
411 MissingContentLength (client): You must provide the Content-Length HTTP head
er. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MissingContentLength</Code><Message>You must provide the Content-Le
ngth HTTP header.</Message><RequestId>...</RequestId><HostId>...</HostId><
/Error> in /path/to/aws/aws-sdk-php/src/S3/StreamWrapper.php on line 735
```

### LINKED ISSUE #3277: GET request with stream option to media.licdn.com returns 500
**Guzzle version(s) affected**: 7.9.2
**PHP version**: 8.3.19 (hint: `php --version`)
**cURL version**: 8.12.1 (hint: `php -i | grep cURL`)

**Description**  
When requesting any asset from Linkedin CDN and trying to use the `'stream' => true` option, you only get a 500 error back.

**How to reproduce**  
```php
<?php declare(strict_types = 1);

require __DIR__ . '/vendor/autoload.php';

$url = $argv[1] ?? null;

if (!$url) {
    throw new RuntimeException('No URL provided');
}

use GuzzleHttp\Client;
use GuzzleHttp\RequestOptions;

$client = new Client();
$response = $client->get($url, [
    RequestOptions::STREAM => true,
]);

echo $response->getStatusCode(), "\n";
```

Run this with any sample URL pointing to their CDN, e.g. visit a random public feed and copy the URL to an asset

<details><summary>Example</summary>

```
 $ php guzzle_streaming_test.php 'https://media.licdn.com/dms/image/v2/D4D10AQFG-4c4WEwEWg/ads-video-thumbnail_720_1280/B4DZW3w64XG8AY-/0/1742544853990?e=1743170400&v=beta&t=MqTW3Uvop_31Sz_qyT_vtNKbNp1F8xYjFdwbow9vMe0'
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://media.licdn.com/dms/image/v2/D4D10AQFG-4c4WEwEWg/ads-video-thumbnail_720_1280/B4DZW3w64XG8AY-/0/1742544853990?e=1743170400&v=beta&t=MqTW3Uvop_31Sz_qyT_vtNKbNp1F8xYjFdwbow9vMe0` resulted in a `500 Internal Server Error` response in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 /vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'https://media.l...', Array)
#11 /guzzle_streaming_test.php(15): GuzzleHttp\Client->get('https://media.l...', Array)
#12 {main}
  thrown in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://media.licdn.com/dms/image/v2/D4D10AQFG-4c4WEwEWg/ads-video-thumbnail_720_1280/B4DZW3w64XG8AY-/0/1742544853990?e=1743170400&v=beta&t=MqTW3Uvop_31Sz_qyT_vtNKbNp1F8xYjFdwbow9vMe0` resulted in a `500 Internal Server Error` response in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 /vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'https://media.l...', Array)
#11 /guzzle_streaming_test.php(15): GuzzleHttp\Client->get('https://media.l...', Array)
#12 {main}
  thrown in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111
```
</details>

**Possible Solution**  
After some debugging I found at that when I remove this line, it works https://github.com/guzzle/guzzle/blob/fcac7bafca20027859d7096a5d25959b75885671/src/Handler/StreamHandler.php#L58

This was introduced with https://github.com/guzzle/guzzle/commit/f9614178a7e9f1afbbce41f2e4142cd1d85d8172 respectively https://github.com/guzzle/guzzle/commit/1bf94e4f807588911c6a44e8f82b8602a480b375 which came from https://github.com/aws/aws-sdk-php/issues/701

Here's the output when I remove it:
```
 $ php guzzle_streaming_test.php 'https://media.licdn.com/dms/image/v2/D4D10AQFG-4c4WEwEWg/ads-video-thumbnail_720_1280/B4DZW3w64XG8AY-/0/1742544853990?e=1743170400&v=beta&t=MqTW3Uvop_31Sz_qyT_vtNKbNp1F8xYjFdwbow9vMe0'
200
```

### PR DESCRIPTION
**Pull request by mfn**
## Summary
Fixes #3277 and reverts #1189

Originally this was introduced in #1189 to fix https://github.com/aws/aws-sdk-php/issues/701

In my case however, I receive a 500 when trying to stream content from media.licdn.com because of this header.

I then went back and tried the example from the aws-sdk-php and removed that header only to learn it works as expected.

My conclusion therefore is that in the past 10 years either AWS server or the SDK changed and this workaround, once needed, no longer is necessary and we can remove it.

### Update
- The final PR only removes the content-length header for `GET` requests, keeps it for `POST` & `PUT`

### CODE REVIEW

**Comment by mfn** [comment]
CI fails for unrelated reason, I see this locally too [and other tests are failing](https://github.com/guzzle/guzzle/actions/runs/13981481062/job/39147439887), too 

> ```
> There was 1 failure:
> 
> 1) GuzzleHttp\Test\Handler\StreamHandlerTest::testHandlesGarbageHttpServerGracefully
> Failed asserting that exception of type "GuzzleHttp\Exception\ConnectException" matches expected exception "GuzzleHttp\Exception\RequestException". Message was: "Connection refused for URI http://127.0.0.1:8126/guzzle-server/garbage" at
> /home/runner/work/guzzle/guzzle/src/Handler/StreamHandler.php:329
> /home/runner/work/guzzle/guzzle/src/Handler/StreamHandler.php:242
> /home/runner/work/guzzle/guzzle/src/Handler/StreamHandler.php:323
> /home/runner/work/guzzle/guzzle/src/Handler/StreamHandler.php:58
> /home/runner/work/guzzle/guzzle/tests/Handler/StreamHandlerTest.php:760
> .
> 
> FAILURES!
> Tests: 563, Assertions: 2313, Failures: 1, Skipped: 8.
> ```

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Does cURL still have this behaviour? We were matching it on purpose, surely? I don't think our stream handler and curl handler should behave differently here.

**Comment by mfn** [comment]
I see, you mean `\GuzzleHttp\Handler\CurlFactory` via `\GuzzleHttp\Handler\CurlHandler` probably. Thanks, the initial PR says:
> Curl will assign a content-length header of '0' when it's missing from a request

But I was not in the clear what this means (libcurl itself??).

Now I re-checked and found this https://github.com/guzzle/guzzle/blob/40ad735f966e6a5b22162e53e1bcb5f520bf52eb/src/Handler/CurlFactory.php#L342-L346

It only triggers on PUT & POST, but **not** on `GET` which would also satisfy my requirement, I've pushed an update!

File: src/Handler/StreamHandler.php [hunk 1]
```diff
@@ -53,8 +53,14 @@ public function __invoke(RequestInterface $request, array $options): PromiseInte
             $request = $request->withoutHeader('Expect');
 
             // Append a content-length header if body size is zero to match
-            // cURL's behavior.
-            if (0 === $request->getBody()->getSize()) {
+            // the behavior of `CurlHandler`
+            if (
+                (
+                    0 === \strcasecmp('PUT', $request->getMethod()) ||
+                    0 === \strcasecmp('POST', $request->getMethod())
```
Comment (mfn) [inline src/Handler/StreamHandler.php]: Used `strcasecmp` to match what's used in `createResponse` (in this file) when checking for `HEAD`

File: tests/Handler/StreamHandlerTest.php [hunk 2]
```diff
@@ -554,6 +554,26 @@ public function testAddsContentLengthEvenWhenEmpty()
...
+    }
+
+    public function testDontAddContentLengthForGETEvenWhenEmpty()
+    {
+        $this->queueRes();
+        $handler = new StreamHandler();
+        $request = new Request('GET', Server::$url, [], '');
+        $handler($request, []);
+        $req = Server::received()[0];
+        self::assertSame('', $req->getHeaderLine('Content-Length'));
```
Comment (mfn) [inline tests/Handler/StreamHandlerTest.php:574]: This is the effect of my change, otherwise this would be
```suggestion
        self::assertSame(0, $req->getHeaderLine('Content-Length'));
```

**Comment by mfn** [comment]
Unrelated failing (Linux) tests are fixed with https://github.com/guzzle/guzzle/pull/3280

**Comment by GrahamCampbell** [comment]
Thanks. I'll look to get a release out, soon.

**Comment by mfn** [comment]
Thanks, appreciated; didn't realize the last release was already so long ago.

Not everything without releases is abandoned, sometimes software is just super stable :)
