### PR TITLE
[6.5] Don't use internal functions

### LINKED ISSUE #2511: Call to undefined function GuzzleHttp_idn_uri_convert()
Hello - after the December 2019 updates, we are receiving the following error. Our client code calls into Guzzle at #2, so we don't call GuzzleHttp_idn_uri_convert() directly:

[28-Dec-2019 17:57:20 UTC] PHP Fatal error: Uncaught Error: Call to undefined function GuzzleHttp_idn_uri_convert() in wp-content/plugins/q4vrplugin/vendor/guzzlehttp/guzzle/src/Client.php:220
Stack trace:
#0 guzzlehttp/guzzle/src/Client.php(155): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array)

#1 guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync('GET', 'units', Array)

#2 plugin/Models/ApiClient.php(97): GuzzleHttp\Client->request('GET', 'units', Array)

Please let me know what additional information I can provide to assist.

Thanks!

Jim

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Since these functions are internal, this should not be an issue. We maybe could even delete those functions in 7.0.0, outright. A more complete version is available at https://github.com/guzzle/guzzle/pull/2546, targetted at 7.0, since it does the same for the non-internal functions.

---

Fixes #2511.

### CODE REVIEW

File: src/Utils.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    {
+        if ($uri->getHost()) {
+            $idnaVariant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : 0;
+            $asciiHost = $idnaVariant === 0
+                ? idn_to_ascii($uri->getHost(), $options)
+                : idn_to_ascii($uri->getHost(), $options, $idnaVariant, $info);
+            if ($asciiHost === false) {
+                $errorBitSet = isset($info['errors']) ? $info['errors'] : 0;
+
+                $errorConstants = array_filter(array_keys(get_defined_constants()), function ($name) {
```
Comment (phansys) [inline src/Utils.php]:
```suggestion
                $errorConstants = array_filter(array_keys(get_defined_constants()), static function ($name) {
```

File: src/Utils.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+                    }
+                }
+
+                $errorMessage = 'IDN conversion failed';
+                if ($errors) {
+                    $errorMessage .= ' (errors: ' . implode(', ', $errors) . ')';
+                }
+
+                throw new InvalidArgumentException($errorMessage);
+            } else {
```
Comment (phansys) [inline src/Utils.php]: IMO, this `else` clause is superfluous and can be safely omitted.

File: src/Utils.php (hunk 1 above)
Comment (GrahamCampbell) [reply src/Utils.php]: Not making any code changes. We can do this on 7.x. This is strictly a bug fix PR for 6.5.x.

File: src/Utils.php (hunk 2 above)
Comment (GrahamCampbell) [reply src/Utils.php]: Not making any code changes. We can do this on 7.x. This is strictly a bug fix PR for 6.5.x.

Comment (GrahamCampbell) [reply src/Utils.php]: All I'm doing is moving the code around, and not changing it.

**Comment by Nyholm** [comment]
Thank you again @GrahamCampbell
